version: "3"
services:
  dev:
    build: 
      context: ../
      dockerfile: Dockerfile_dev
    command: tail -F anything
    volumes:
      - ../tf_sms/src:/ws/src/tf_sms/src
      - ../tf_bringup/:/ws/src/tf_bringup/
      - ../tf_broadcast/:/ws/src/tf_broadcast/
      - ../tf_lookup/:/ws/src/tf_lookup/
      - ../tf_tools_msgs/:/ws/src/tf_tools_msgs/
      
